version: '2'

services:
    revp:
      image: dnginx/withconf:latest
      ports: 
        - "80:80"
        - "443:443"
      depends_on:
        - reg
      links:
        - reg
    reg:
      image: registry
      expose: 
        - 5000
      volumes:
        - "/root/reg-data:/var/lib/registry:rw"
