version: '2'

services:
    api-service:
        build: 
            context: ./TodoAPI
            dockerfile: Dockerfile
        image: test/todo:latest        

    todonginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: dnginx/withconf:latest            