apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - mountPath: /data/db
      name: mongo-volume
  volumes:
  - name: mongo-volume
    hostPath:
      # directory location on host
      #path: E:\POC\sharedVolume
      path: E:\POC\sharedVolume
      # this field is optional
      #type: DirectoryOrCreate
      type: Directory