kind: PersistentVolume
apiVersion: v1
metadata:
  name: demo
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-080316a351466b56e
    fsType: ext4