apiVersion: v1
kind: Service
metadata: 
  name: mongodb-service
  labels: 
    name: mongodb-service
spec: 
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30017
  selector: 
    app: mongodb