kind: PersistentVolume
apiVersion: v1
metadata:
  name: demo
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/efs"