apiVersion: v1
kind: Service
metadata: 
  name: mongoservice
  labels: 
    name: mongoservice
spec: 
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 27017
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    app: mongo