apiVersion: v1
kind: Service
metadata: 
  name: mongodb-client-service
  labels: 
    name: mongodb-client-service
spec: 
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30003
  selector: 
    app: mongodb-client