apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
        app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        tier: database
    spec:
      containers:
      - image: mongo
        name: mongodb        
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: demo
          mountPath: /data/db
      volumes:
      - name: demo
        persistentVolumeClaim:
          claimName: demo
